### ISSUE TITLE
Handle DB migrations

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/caseDB#46]
We need to figure out how to do database migrations. Right now, sql statements in `.sql` files seem adequate but this could get out of hand fast. Especially if we decide to change the schema (which is quite likely). I've heard good things about `prisma` being quite good for migrations. **We will definitely not use `prisma` as an ORM** but we may look into how we can utilize its migration capabilities.

**Comment by protibimbok** [comment]
If we want to create a system just for migrations, that is possible. But that will take a lot of time.
How about we install **pirsma** as a dev dependency and use only the migration feature of it?

**Comment by permafrost06** [comment]
Please install `prisma` and try out some imaginary migrations and report back to me how it goes.

**Comment by permafrost06** [comment]
Drizzle ORM seems to have migrations available via DrizzleKit. Have a look at it.

**Comment by permafrost06** [comment]
closed by #52
