### ISSUE TITLE
Create CRUD for patient

### ISSUE THREAD

**Issue by permafrost06** [permafrost06/caseDB#47]
Make a CRUD the same way it was done for `tests`. The properties are:
1. id -> string ~~(auto increment)  (not sure if string can be auto incremented, let know)~~
1. type -> "histo" | "cyto"
2. status -> "draft" | "pending" | "locked" | "delivered"
1. patient name -> string
1. sample collection date -> date
1. entry date -> date
1. age -> number
1. gender -> "male" | "female"
1. contactNo -> string
1. specimen -> string
1. referer -> string
1. delivery date -> date
1. tests -> []test_ids
1. discount -> number
1. advance -> number
1. timestamp -> datetime

\* Some v2 properties are mapped as follows:
* collDate -> sample collection date
* date -> entry date

\* Some v2 properties are not included here (these can be calculated):
* subtotal
* netPay
* due

Please have a look at v2 app and code and check if anything is missing.

## Possible issues:
* ~~The app will show historical financial statements. How are we going to handle the change in a `test`'s price? Because in the proposed shape here (the financial records will be generated on the fly from `test` ids), changing the price will change the older financial statements.~~

~~Possible solution: We may have an `invoices` table where we store the invoice properties (e.g. hardcoded test id, name, prices etc.)~~
#### Fixed by #51

* ~~This table might be too complex, we might consider breaking this up into multiple tables such as: patients (will only feature patient info), invoice (will only feature invoice properties), record (will combine patient and invoice with other stuff if needed) etc.~~
#### Requirements updated

**Comment by protibimbok** [comment]
Right now, strings cannot be auto incremented. However, we may use uuid to get a similar result.
But if you need strings that goes like this, a,b,....,z,1a,......,1z,2a,..... I can try to achieve this. This might be possible using TRIGGERS.
https://sqlite.org/lang_createtrigger.html

**Comment by permafrost06** [comment]
I'm sure we can find a better solution than triggers. I'll let you know.

**Comment by permafrost06** [comment]
closed by #53
